[package]
name = "mediasoup-example"
version = "0.1.0"
edition = "2021"
lib = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix = "0.12"
actix-web-actors = "4.1.0"
